# Generated by Django 3.2.9 on 2021-11-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='page',
            field=models.CharField(choices=[('INDEX', 'index'), ('SERVICE', 'service'), ('LOCATION', 'location'), ('ABOUT', 'about'), ('CAREER', 'career')], default='index', max_length=10),
        ),
    ]
