# Generated by Django 3.2.9 on 2021-11-26 12:14

import auto.minixs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_ru', models.CharField(max_length=100)),
                ('h3_uz', models.CharField(max_length=100)),
                ('text_ru', models.TextField()),
            ],
            bases=(auto.minixs.TranslateMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='carousel',
            name='title_uz',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
