# Generated by Django 3.2.9 on 2021-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211126_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttext',
            name='text_ru',
            field=models.CharField(max_length=2000),
        ),
    ]
