# Generated by Django 3.2.9 on 2021-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_abouttext_text_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttext',
            name='text_uz',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
