# Generated by Django 3.2.9 on 2021-11-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_abouttext_text_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/about')),
                ('author', models.CharField(max_length=60)),
                ('text', models.TextField()),
            ],
        ),
    ]
