# Generated by Django 3.2.9 on 2021-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_uz',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
