# Generated by Django 3.2.9 on 2021-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211126_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttext',
            name='entrance_h3',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttext',
            name='entrance_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
