# Generated by Django 3.2.9 on 2021-11-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211128_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abouttext',
            old_name='entrance_text',
            new_name='entrance_textru',
        ),
        migrations.RenameField(
            model_name='abouttext',
            old_name='entrance_h3',
            new_name='entrance_uz',
        ),
        migrations.AddField(
            model_name='abouttext',
            name='entrance_ru',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttext',
            name='entrance_textuz',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
