# Generated by Django 3.2.9 on 2021-11-28 17:47

import auto.minixs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211128_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_ru', models.CharField(max_length=150)),
                ('entrance_uz', models.CharField(max_length=150)),
                ('entrantext_ru', models.TextField()),
                ('entrantext_uz', models.TextField()),
            ],
            bases=(auto.minixs.TranslateMixin, models.Model),
        ),
    ]
