# Generated by Django 3.2.9 on 2021-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_entranceabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='page',
            field=models.CharField(blank=True, choices=[('INDEX', 'index'), ('SERVICE', 'service'), ('LOCATION', 'location'), ('ABOUT', 'about'), ('CAREER', 'career')], max_length=10, null=True),
        ),
    ]
