# Generated by Django 3.2.9 on 2021-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='work',
            field=models.CharField(blank=True, choices=[('Air', 'air'), ('Ceramic', 'ceramic'), ('Dry', 'dry')], max_length=10, null=True),
        ),
    ]
